# Generated by Django 2.2.12 on 2020-09-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20200918_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='date_of_establishment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='تاريخ سنة التأسيس'),
        ),
    ]
