# Generated by Django 2.2.12 on 2020-09-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20200918_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
