# Generated by Django 2.2.12 on 2020-09-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20200918_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
