# Generated by Django 2.2.12 on 2020-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_auto_20200920_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='logo',
            field=models.ImageField(default='org_logos/default_logo.jpg', upload_to='org_logos', verbose_name='شعار المنظمة'),
        ),
    ]
