# Generated by Django 3.1.1 on 2020-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_auto_20200920_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='email_person_contact',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='البريد الاكتروني للشخص المسؤول عن التواصل'),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='site_web',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='الموقع الالكتروني'),
        ),
    ]
