# Generated by Django 3.1.1 on 2020-10-14 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0010_auto_20200923_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الخبر')),
                ('content', models.TextField(max_length=5000, verbose_name='تفاصيل الخبر')),
                ('image', models.ImageField(default='news_images/article_img.jpg', upload_to='news_images', verbose_name='صورة الخبر')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('org_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
