# Generated by Django 3.1.1 on 2020-10-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_orgnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgnews',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
