# Generated by Django 3.1.1 on 2020-10-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_orgnews_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgnews',
            old_name='date_published',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='orgnews',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='orgnews',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
