# Generated by Django 3.1.1 on 2020-10-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_auto_20201016_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
