# Generated by Django 3.1.1 on 2020-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_auto_20201016_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrapport',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
