# Generated by Django 3.1.1 on 2020-10-17 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0018_otgdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtgData',
            new_name='OrgData',
        ),
    ]
