# Generated by Django 3.1.1 on 2020-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_auto_20201020_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgresearch',
            name='org_name',
        ),
        migrations.AddField(
            model_name='orgresearch',
            name='name_entity',
            field=models.CharField(default='SCM', max_length=255, verbose_name='اسم الجهة'),
        ),
    ]
