# Generated by Django 3.1.1 on 2020-10-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_auto_20201021_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgresearch',
            name='name_entity',
            field=models.CharField(max_length=255, verbose_name='اسم الجهة'),
        ),
    ]
