# Generated by Django 3.1.1 on 2020-10-24 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0023_auto_20201021_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='عنوان الوظيفة')),
                ('period_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة العقد بالأشهر')),
                ('job_description', models.TextField(max_length=5000, verbose_name='وصف الوضيفة')),
                ('job_type', models.CharField(choices=[('Full time', 'دوام كامل'), ('Part time', 'دوام جزئي'), ('Expert', 'استشاري'), ('Traning', 'تدريب'), ('Volunteering', 'تطوع'), ('Fellowship', 'زمالة')], max_length=255, verbose_name='نوع الوظيفة')),
                ('experience', models.CharField(choices=[('Not necessary', 'الخبرة غير ضرورية'), ('1-2 year', '1-2 سنة'), ('2-5 years', '2-5 سنة'), ('5-9 years', '5-9 سنة'), ('up of 10 years', '10 وفوق'), ('Othre', 'أخرى')], max_length=255, verbose_name='الخبرة')),
                ('job_country', django_countries.fields.CountryField(max_length=255, verbose_name='مكان العمل')),
                ('job_city', models.CharField(blank=True, choices=[('aleppo', 'حلب'), ('damascus', 'دمشق'), ('suburb of damascus', 'ريف دمشق'), ('daraa', 'درعا'), ('deir ez-Zor', 'دير الزور'), ('hama', 'حماه'), ('al-Hasakah', 'الحسكة'), ('homs', 'حمص'), ('idlib', 'إدلب'), ('latakia', 'اللاذقية'), ('quneitra', 'القنيطرة'), ('raqqa', 'الرقة'), ('as-Suwayda', 'السويداء'), ('tartus', 'طرطوس')], max_length=150, null=True, verbose_name='المحافظة')),
                ('job_area', models.CharField(blank=True, max_length=150, null=True, verbose_name='المنطقة')),
                ('job_domain', models.CharField(choices=[('Media', 'إعلام'), ('Education', 'تعليم'), ('Protection', 'حماية'), ('Livelihoods and food security', 'سبل العيش واﻷمن الغذائي'), ('Project of clean ,water, sanitation ', 'مشاريع النظافة والمياه والصرف الصحي'), ('Development', 'تنمية'), ('Law, suport, policy', 'قانون و مناصرة و سیاسة'), ('Donors and support volunteering', 'مانحین و دعم العمل التطوعي'), ('Religious org', 'منظمات دینیة'), ('Prof association and assembles', 'تجمعات و اتحادات مھنیة'), ('Health', 'صحة'), ('Studies and research', 'دراسات وأبحاث'), ('Other', 'أخرى')], max_length=255, verbose_name='مجال العمل')),
                ('dead_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاريخ إغلاق الوظيفة')),
                ('job_aplay', models.TextField(max_length=5000, verbose_name='طريقة التقدم للوظيفة')),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('org_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
