# Generated by Django 3.1.1 on 2020-10-27 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0024_orgjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgFundingOpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_funding', models.CharField(max_length=255, verbose_name='الجهة المانحة')),
                ('logo_funding', models.ImageField(default='org_logos/default_logo.jpg', upload_to='funding_logos', verbose_name='لوغو الجهة المانحة')),
                ('funding_org_description', models.TextField(max_length=2000, verbose_name='لمحة عن الجهة المانحة')),
                ('work_domain', models.CharField(choices=[('Media', 'إعلام'), ('Education', 'تعليم'), ('Protection', 'حماية'), ('Livelihoods and food security', 'سبل العيش واﻷمن الغذائي'), ('Project of clean ,water, sanitation ', 'مشاريع النظافة والمياه والصرف الصحي'), ('Development', 'تنمية'), ('Law, suport, policy', 'قانون و مناصرة و سیاسة'), ('Donors and support volunteering', 'مانحین و دعم العمل التطوعي'), ('Religious org', 'منظمات دینیة'), ('Prof association and assembles', 'تجمعات و اتحادات مھنیة'), ('Health', 'صحة'), ('Studies and research', 'دراسات وأبحاث'), ('Other', 'أخرى')], max_length=255, verbose_name='قطاع المنحة')),
                ('funding_country', django_countries.fields.CountryField(max_length=255, verbose_name='دول المنحة')),
                ('funding_city', models.CharField(blank=True, choices=[('aleppo', 'حلب'), ('damascus', 'دمشق'), ('suburb of damascus', 'ريف دمشق'), ('daraa', 'درعا'), ('deir ez-Zor', 'دير الزور'), ('hama', 'حماه'), ('al-Hasakah', 'الحسكة'), ('homs', 'حمص'), ('idlib', 'إدلب'), ('latakia', 'اللاذقية'), ('quneitra', 'القنيطرة'), ('raqqa', 'الرقة'), ('as-Suwayda', 'السويداء'), ('tartus', 'طرطوس')], max_length=150, null=True, verbose_name='المحافظة')),
                ('funding_dead_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='تاريخ إغلاق المنحة')),
                ('funding_period', models.PositiveIntegerField(blank=True, choices=[('less of 6 months', 'أقل من 6 أشهر'), ('from 6 mths to one year', 'ستة أشهر لسنة'), ('from one to 2 years', 'سنة إلى سنتين'), ('more than 2 years', 'أكثر من سنتين'), ('other', 'أخرى')], null=True, verbose_name='مدة المنحة')),
                ('funding_amounte', models.PositiveIntegerField(blank=True, choices=[('less than 5000 ', 'أقل من 5000 دولار'), ('from 5000 to 10000 dollar', 'بين 5000 و 10000 دولار'), ('from 10000 to 50000', 'بين 10000 و50000 دولار'), ('from 50000 to 100000', 'بين 50000 و100000 دولار'), ('more than  100000', 'بين 50000 و100000 دولار'), ('other', 'أخرى')], null=True, verbose_name=' حجم المنحة')),
                ('funding_description', models.TextField(max_length=2000, verbose_name='صف المنحة')),
                ('funding_conditions', models.TextField(max_length=2000, verbose_name='شروط المنحة')),
                ('funding_reqs', models.TextField(max_length=2000, verbose_name='متطلبات التقديم')),
                ('funding_guid', models.TextField(max_length=2000, verbose_name='كيفية التقديم')),
                ('funding_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='الرابط الأصلي')),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
