# Generated by Django 3.1.1 on 2020-10-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='position_work',
            field=models.CharField(blank=True, choices=[('IQ', 'العراق'), ('LB', 'لبنان'), ('JO', 'اﻷردن'), ('SY', 'سوريا'), ('TR', 'تركيا')], max_length=150, null=True, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='city_work',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.city', verbose_name='المحافظة'),
        ),
    ]
