# Generated by Django 3.1.1 on 2020-10-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_auto_20201024_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='position_work',
            field=models.CharField(choices=[('IQ', 'العراق'), ('LB', 'لبنان'), ('JO', 'اﻷردن'), ('SY', 'سوريا'), ('TR', 'تركيا')], default=None, max_length=150, verbose_name='الدولة'),
        ),
    ]
