# Generated by Django 3.1.1 on 2020-10-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_orgfundingopp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgfundingopp',
            name='funding_dead_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إغلاق المنحة'),
        ),
    ]
