# Generated by Django 3.1.1 on 2020-10-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_auto_20201024_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='city_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.city', verbose_name='المحافظة'),
        ),
    ]
