# Generated by Django 3.1.1 on 2020-10-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0027_auto_20201027_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgfundingopp',
            name='org_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile'),
        ),
    ]
