# Generated by Django 3.1.1 on 2020-10-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0027_auto_20201024_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='city_work',
        ),
    ]
