# Generated by Django 3.1.1 on 2020-10-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0028_orgfundingopp_org_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgfundingopp',
            name='logo_funding',
        ),
    ]
