# Generated by Django 3.1.1 on 2020-10-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0029_orgrapport_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم و الكنية')),
                ('work', models.CharField(max_length=255, verbose_name='العمل')),
                ('org_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المنظمة')),
                ('email', models.EmailField(max_length=255, verbose_name='البريد الاكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
