# Generated by Django 3.1.1 on 2020-10-28 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0029_remove_orgfundingopp_logo_funding'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgCapacityOpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_capacity', models.CharField(max_length=255, verbose_name='اسم الجهة الممولة')),
                ('title_capacity', models.CharField(max_length=255, verbose_name='عنوان الفرصة')),
                ('capacity_description', models.TextField(max_length=2000, verbose_name='وصف الفرصة')),
                ('capacity_type', models.CharField(choices=[('traning', 'تدريب'), ('college', 'زمالة')], max_length=255, verbose_name='نوع الفرصة')),
                ('capacity_country', django_countries.fields.CountryField(max_length=255, verbose_name='مكان الفرصة')),
                ('capacity_city', models.CharField(blank=True, choices=[('aleppo', 'حلب'), ('damascus', 'دمشق'), ('suburb of damascus', 'ريف دمشق'), ('daraa', 'درعا'), ('deir ez-Zor', 'دير الزور'), ('hama', 'حماه'), ('al-Hasakah', 'الحسكة'), ('homs', 'حمص'), ('idlib', 'إدلب'), ('latakia', 'اللاذقية'), ('quneitra', 'القنيطرة'), ('raqqa', 'الرقة'), ('as-Suwayda', 'السويداء'), ('tartus', 'طرطوس')], max_length=150, null=True, verbose_name='المحافظة')),
                ('capacity_domain', models.CharField(choices=[('Media', 'إعلام'), ('Education', 'تعليم'), ('Protection', 'حماية'), ('Livelihoods and food security', 'سبل العيش واﻷمن الغذائي'), ('Project of clean ,water, sanitation ', 'مشاريع النظافة والمياه والصرف الصحي'), ('Development', 'تنمية'), ('Law, suport, policy', 'قانون و مناصرة و سیاسة'), ('Donors and support volunteering', 'مانحین و دعم العمل التطوعي'), ('Religious org', 'منظمات دینیة'), ('Prof association and assembles', 'تجمعات و اتحادات مھنیة'), ('Health', 'صحة'), ('Studies and research', 'دراسات وأبحاث'), ('Other', 'أخرى')], max_length=255, verbose_name='قطاع الفرصة')),
                ('capacity_dead_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إغلاق المنحة')),
                ('capacity_reqs', models.TextField(max_length=2000, verbose_name='متطلبات التقديم')),
                ('capacity_guid', models.TextField(max_length=2000, verbose_name='طريقة التقديم')),
                ('capacity_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='الرابط الأصلي')),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('org_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
